language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

matrix:
    include:
        - python: 2.7

install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels defaults
    - conda config --add channels astropy-ci-extras
    - conda update conda
    - conda create -n test python=2.7
    - source activate test
    - conda search astropy
    - conda install numpy
    - conda install python=2.7 astropy

script:
    - python -c 'import numpy'

