language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='pyqt nose matplotlib pillow'
        - PIP_DEPENDENCIES='pytest-mpl'
        - SETUP_XVFB=True
        - DEBUG=True

matrix:
    include:
        - python: 2.7
          env: SETUP_CMD='test --coverage --remote-data'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - python -c 'import numpy'
    - python -c 'import astropy'

after_success:
    - if [[ $SETUP_CMD == 'test --coverage --remote-data' ]]; then
          coveralls --rcfile='wcsaxes/tests/coveragerc';
      fi
